post_install(){
rm /usr/share/gnome-background-properties/adwaita.xml
rm /usr/share/gnome-background-properties/gnome-default.xml
rm -r /usr/share/backgrounds/gnome
mv /usr/share/backgrounds/apricity/ /usr/share/backgrounds/gnome
rm /usr/share/gnome-background-properties/gnome-backgrounds.xml
cp /usr/share/gnome-background-properties/apricity-backgrounds.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
chmod -R 755 /usr/share/backgrounds/gnome
kwriteconfig --file kdeglobals --group General --key widgetStyle gtk && kwriteconfig --file kdeglobals --group Icons --key Theme Human
chown -R root /etc/apricity-assets
chmod -R 755 /etc/apricity-assets
chmod 755 /usr/share
chmod 755 /usr/share/applications
chmod 755 /usr/lib
chmod 755 /etc
}

post_remove(){
rm -r "/usr/share/themes/Arctic Apricity"
rm -r "/usr/share/icons/Apricity Icons"
rm -r /usr/share/backgrounds/apricity
rm -r /etc/skel/.liquidprompt
rm -r /usr/share/plymouth/themes/apricity
rm /etc/skel/.config/autostart/firstrun.sh
rm /etc/skel/.config/autostart/firstrun.desktop
rm /usr/share/gnome-background-properties/apricity-backgrounds.xml
rm -r /etc/apricity-assets
}

pre_upgrade(){
rm -r "/usr/share/themes/Arctic Apricity"
rm -r "/usr/share/icons/Apricity Icons"
rm -r /usr/share/backgrounds/apricity
rm -r /etc/skel/.liquidprompt
rm -r /usr/share/plymouth/themes/apricity
rm /etc/skel/.config/autostart/firstrun.sh
rm /etc/skel/.config/autostart/firstrun.desktop
rm /usr/share/gnome-background-properties/apricity-backgrounds.xml
rm -r /etc/apricity-assets
}

post_upgrade(){
rm /usr/share/gnome-background-properties/adwaita.xml
rm /usr/share/gnome-background-properties/gnome-default.xml
rm -r /usr/share/backgrounds/gnome
mv /usr/share/backgrounds/apricity/ /usr/share/backgrounds/gnome
rm /usr/share/gnome-background-properties/gnome-backgrounds.xml
cp /usr/share/gnome-background-properties/apricity-backgrounds.xml /usr/share/gnome-background-properties/gnome-backgrounds.xml
chown -R root /etc/apricity-assets
chmod 755 /etc/apricity-assets
chmod -R 755 /usr/share/backgrounds/gnome
kwriteconfig --file kdeglobals --group General --key widgetStyle gtk && kwriteconfig --file kdeglobals --group Icons --key Theme Human
chown -R root /etc/apricity-assets
chmod -R 755 /etc/apricity-assets
chmod 755 /usr/share
chmod 755 /usr/share/applications
chmod 755 /usr/lib
chmod 755 /etc
}
